### ISSUE TITLE
User access removed, access is now via a team

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cjsm#7]
Hi there 

 This user had Direct Member access to this repository and access via a team. 

 Access is now only via a team. 

 If you have any questions, please post in #ask-operations-engineering on Slack. 

 This issue can be closed.

**Comment by DianeAldsworth** [comment]
@AntonyBishop please can I have some context to this?  Is this about OneTrust?  If not, what please? Thanks

**Comment by NickWalt01** [comment]
Hello 

This a policy MoJ we are starting to enforce, users should be allocated to a team and that team shall have access to the repositories.

Regards
Nick

**Comment by DianeAldsworth** [comment]
Thanks @NickWalt01 - but still don't know why this has been assigned to me???

**Comment by NickWalt01** [comment]
Your username was attached to this repo directly and through a team, our automation detected that and has removed your direct connection and now you can access the repo through a team you are a member of. I assume you are still part of the MoJ ?

**Comment by DianeAldsworth** [comment]
I am - but I've no idea what repo I was a member of???

**Comment by NickWalt01** [comment]
the issue we are talking in is in this repo, it is called cjsm

**Comment by DianeAldsworth** [comment]
Ah yes! I do remember - David Read created it for the CJSM micro site. Thanks :)
